/mnt/HC_Volume_106659003/sol-drivechain/betanet/*.log
/mnt/HC_Volume_106659003/sol-drivechain/regtest/*.log
/mnt/HC_Volume_106659003/sol-drivechain/regtest/bitcoin-stack/enforcer/enforcer.log
/mnt/HC_Volume_106659003/sol-drivechain/regtest/bitcoin-stack/bitcoin/regtest/debug.log {
    size 100M
    rotate 5
    compress
    delaycompress
    copytruncate
    missingok
    notifempty
}
